### ISSUE TITLE
Move to posthtml organization

### ISSUE THREAD

**Issue by stevenvachon** [posthtml/posthtml-urls#1]
@michael-ciniawsky wanna help set me up?

**Comment by michael-ciniawsky** [comment]
@stevenvachon Oh yes awesome, that was on the list anyways 😛 First of all, could we agree upon renaming `posthtml-url-attrs` to `posthtml-url`?

I must review your approach first, so this is completely out of the blue, but I had something like that in mind 

```html
<link cdn="lib.css">
<link npm="lib.css">
<link bower="lib.css">
<link domain="index.css">

<img cdn="img.png">


<script cdn="lib.js"></script>
<script npm="lib.css"></script>
<script bower="lib.css"></script>
<script domain="index.js"></script>
```


```js
const options = {
   cdn: [ 'https://mycdn.com', {  link: 'href', script: 'src', img: 'src' } ],
   npm: [ 'node_modules', {...} ],
   bower: ['bower_components', {...} ],
   domain: [ 'https://mysite.com',  { link: 'href', script: 'src' } ],
   ...   
}

posthtml([ url(options) ]).process(html).then((result) => result)
```

Although I'm not 💯 happy with the options object yet, and some of the examples above are defaults of course 😛

**Comment by stevenvachon** [comment]
That's pretty different from what I was designing. I didn't want to extend HTML, but instead provide a simple tool for transforming the values of standard HTML attributes that expect URLs.

The filtering can be customized, so that a different callback with different transformations could be called.

It's kind of a dependency for other URL-centric posthtml plugins.

**Comment by stevenvachon** [comment]
Also, your custom attribute idea only seems to account for the common URL attribute for each element, such as `src` or `href`, and not the less common, such as `srcset`. Consider this:

```html
<img src="image.png" srcset="image.svg 2x">
```

---

Maybe the attributes need only be prefixed:
```html
<img cdn-src="image.png" cdn-srcset="image.svg 2x">
<script cdn-src="index.js"></script>
```

**Comment by michael-ciniawsky** [comment]
> That's pretty different from what I was designing. I didn't want to extend HTML, but instead provide a simple tool for transforming the values of standard HTML attributes that expect URLs

Yep, I understand. My current approach is not the best to be honest and I like the idea of a transform/replace via functions, the question is how to target nodes at best

```
const options = {
  default: (url) => url // eachURL (all urls)
  cdn: (selector, url) => ? // selector "{ tag: attr }" ( that's crap atm tbh :) )
}
```

But could you please show me a few basic usage examples please ? 

> It's kind of a dependency for other URL-centric posthtml plugins

More in the direction of a plugin util ? If let's work on a posthtml-plugin-utils module instead :)

> That's pretty different from what I was designing. I didn't want to extend HTML, but instead provide a simple tool for transforming the values of standard HTML attributes that expect URLs.

You set them as `{tag: attr}` pair e.g 

```html
<picture>
 <source cdn="logo-wide.png" media="(min-width: 600px)">
 <img cdn="logo-narrow.png" alt="Logo">
</picture>
```


```
const options = {
  cdn: ['https://mycdn.com', { source: 'srcset', img: 'src' } ]
}
```


```html
<picture>
 <source srcset="https://mycdn.com/logo-wide.png" media="(min-width: 600px)">
 <img src="https://mycdn.com/logo-narrow.png" alt="Logo">
</picture>
```

**Comment by stevenvachon** [comment]
You've confused `<img srcset>` with `<source srcset>`. `<img>` can have *both* `src` and `srcset`.

Most of the time, `<picture>` is not what we want. `<img>` and `<figure>` are much better.

---

> But could you please show me a few basic usage examples please ?

Check out the test suite.

> More in the direction of a plugin util ? If let's work on a posthtml-plugin-utils module instead :)

Perhaps, but how many libs need to transform URL attributes? It might be bloat.

**Comment by stevenvachon** [comment]
> But could you please show me a few basic usage examples please ?
Check out the test suite.

> More in the direction of a plugin util ? If let's work on a posthtml-plugin-utils module instead :)
Perhaps, but how many libs need to transform URL attributes? It might be bloat.

**Comment by michael-ciniawsky** [comment]
> <img> can have both src and srcset

```js
const options = {
  cdn: ['https://mycdn.com', { source: 'srcset', img: 'src', img: 'srcset' } ] // or an Array
}
```

But that's to verbose, there must be an easier way for selections 😛 

Anyways we basically agree on the name change ? I will send PR with README Boilerplate then, leaving the content of course and chore like that, functional URL transforms is fine for getting started we can always enhance from there, but not sure how atm

```js
var options = {
   cdn: ('href' , url) => { attr: 'href', url: url }
}
```

`options.filterCSS ` is debatable imho, a filter is fine but nodes with inline content shouldn't have a `href, src, srcset` attr anyways

**Comment by stevenvachon** [comment]
I just renamed it to "posthtml-urls"  as we have plurally-named libs like "posthtml-classes" already.

`options.filterCSS` is for `background-image:url()`, etc.

**Comment by stevenvachon** [comment]
`filterCSS` is for `background-image:url()`, etc.

**Comment by stevenvachon** [comment]
I created an issue for the attributes idea: #2

I changed it a bit to suite some of our discussions in here.

**Comment by stevenvachon** [comment]
I just tried moving the repo, and it gave me this:
```
You don’t have the permission to create repositories on posthtml
```

**Comment by michael-ciniawsky** [comment]
> "posthtml-url" or "posthtml-urls" ?

`posthtml-url` because of it's cousin `postcss-url` 👍 

> options.filterCSS is for background-image:url(), etc.

Please don't 😛 . There is posthtml-postcss + `postcss-url`or posthtml-content with `postcss` + `postcss-url`, focus should be on HTML

> You don’t have the permission to create repositories on posthtml

@voischev please add @stevenvachon to posthtml/collaborators and give him access to this/his repo then 🙏 😉 


I comment on a few nitpick/bikesheds later :trollface: , I'm sry but a few folks at the ref camp waiting for me, I have to leave the cage for know 😛

**Comment by stevenvachon** [comment]
If we go with `posthtml-url`, then we'll need `url = require("posthtml-url")` and that causes conflicts with other vars that may need that name, such as the transformation function argument, or `require("url")`.

We could also have naming conflicts with the callback's `url` argument.

**Comment by voischev** [comment]
@michael-ciniawsky ok!

**Comment by stevenvachon** [comment]
~~@voischev please enable this repo on travis~~

Oops, never mind; it's already set up.

**Comment by stevenvachon** [comment]
@voischev oops, never mind; it's already set up.

**Comment by stevenvachon** [comment]
~~@voischev please rename this repo to `posthtml-url` when you get a chance.~~

Actually, hold off on that request for now.

Sorry for my constant indecisiveness today. I must be rushing.

**Comment by stevenvachon** [comment]
@voischev actually, hold off on that request for now.

Sorry for my constant indecisiveness today. I must be rushing.

**Comment by michael-ciniawsky** [comment]
@voischev thx :)

@stevenvachon Well both names are totally fine, choose the one you like, but when appropiate, we generally should keep in mind, that 'inofficial' posthtml/postcss naming consistency could be beneficial imho, but it's also not that super important. 

> If we go with posthtml-url, then we'll need url = require("posthtml-url") and that causes conflicts with other vars that may need that name, such as the transformation function argument, or require("url").
> We could also have naming conflicts with the callback's url argument.

In most cases you can name the variable you assign [the plugin] to whatever you want ? 😛 
But I get your point here. e.g `postcss-import/postcss-url` has the same 'issue' with reserved names conflicting. On the other hand `posthtml/postcss-load-config` ('common config') are resolving that, since you don't have to require them directly in your code then.

**Comment by stevenvachon** [comment]
I'll have to think more about the name before I publish, as to avoid having to contact npm to remove anything.

Regarding `posthtml/postcss-load-config`, I personally don't like developing that way, so it doesn't make me feel better about a name with `url` vs `urls`.

**Comment by michael-ciniawsky** [comment]
> I'll have to think more about the name before I publish, as to avoid having to contact npm to remove anything.

Off topic but do you know the official way to do so ? I have few outdated packages mostly with replacements I would like to be removed. Since the `left-pad` 'crisis' their removal policy is ridiculously strict 😞 .

> I'll have to think more about the name before I publish, as to avoid having to contact npm to remove anything.

```js
const $url = require('posthtml-url') // ?

posthtml([ $plugin, $url(), $plugin ]).process(html, options)...
```

or as mentioned via `posthtml.config.js` 😛 

```js
module.exports = (ctx) => ({
  parser: 'posthtml-sugarml',
  plugins: {
    'posthtml-url': {..options}
  }
})
```

**Comment by stevenvachon** [comment]
I've removed one package in the past. I emailed npm and since my package was marked as deprecated, not depended on by any other package, and had around 10 downloads per month, it was an easy decision for them.

I don't like `$` either, haha

**Comment by stevenvachon** [comment]
@voischev @Scrum Would you please add this project to the organization's Coveralls account?

**Comment by Scrum** [comment]
@stevenvachon done

**Comment by stevenvachon** [comment]
@Scrum thanks!

**Comment by Scrum** [comment]
@stevenvachon Yes, I immediately provided them to you. I realized that you are the creator of this package.

Let me know if something goes wrong
