### ISSUE TITLE
Not available on npm?

### ISSUE THREAD

**Issue by zachleat** [posthtml/posthtml-urls#4]
Doesn’t look like this package is available on npm
<img width="346" alt="image" src="https://user-images.githubusercontent.com/39355/35475353-acfab328-0362-11e8-9a16-13f02cf5b080.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/39355/35475354-b06d3fbc-0362-11e8-85d2-387fa730fb41.png">

**Comment by zachleat** [comment]
I, uh, know this is kinda uncool but I went ahead and published this so I could use it 😭

Let me know and I will super-immediately cede control back to you, or add you as a contributor or owner or whatever the NPM lingo is.

https://www.npmjs.com/package/posthtml-urls

(sorry and thank you—this looks great)

**Comment by zachleat** [comment]
Oh goodness, I just read through #1. Lemme know if I did a real bad thing here.

**Comment by stevenvachon** [comment]
@zachleat it was not ready to be published and now it belongs to you on npm. Please transfer ownership to my account: https://npmjs.com/~stevenvachon

**Comment by zachleat** [comment]
Ah yes of course, sorry! I dropped the ball here.

**Comment by stevenvachon** [comment]
😐

**Comment by zachleat** [comment]
I made you an owner—feel free to remove my membership on npm. Looking back it seems ridiculous that I did this—it was a big mistake on my part—again, sorry.

The code has worked well for my project though, so thank you for the project!
